[2024-12-30T06:22:42.710+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:22:42.731+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:22:42.789+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:22:42.778+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:22:42.995+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:22:42.949+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:22:43.000+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:22:43.218+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.666 seconds
[2024-12-30T06:23:14.725+0000] {processor.py:186} INFO - Started process (PID=107) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:23:14.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:23:14.730+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:23:14.730+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:23:14.753+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:23:14.747+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:23:14.755+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:23:14.778+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.062 seconds
[2024-12-30T06:23:45.423+0000] {processor.py:186} INFO - Started process (PID=173) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:23:45.426+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:23:45.429+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:23:45.428+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:23:45.482+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:23:45.469+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:23:45.501+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:23:45.595+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.182 seconds
[2024-12-30T06:24:16.132+0000] {processor.py:186} INFO - Started process (PID=239) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:24:16.134+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:24:16.137+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:24:16.136+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:24:16.162+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:24:16.156+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:24:16.166+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:24:16.218+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.093 seconds
[2024-12-30T06:24:46.498+0000] {processor.py:186} INFO - Started process (PID=306) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:24:46.505+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:24:46.512+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:24:46.510+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:24:46.556+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:24:46.545+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:24:46.559+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:24:46.643+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.182 seconds
[2024-12-30T06:25:17.253+0000] {processor.py:186} INFO - Started process (PID=372) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:25:17.254+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:25:17.256+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:25:17.256+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:25:17.288+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:25:17.278+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:25:17.291+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:25:17.338+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.096 seconds
[2024-12-30T06:25:47.550+0000] {processor.py:186} INFO - Started process (PID=438) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:25:47.552+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:25:47.554+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:25:47.554+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:25:47.576+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:25:47.570+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:25:47.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:25:47.605+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.063 seconds
[2024-12-30T06:26:17.921+0000] {processor.py:186} INFO - Started process (PID=504) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:26:17.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:26:17.928+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:26:17.927+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:26:17.972+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:26:17.960+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:26:17.978+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:26:18.028+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.121 seconds
[2024-12-30T06:26:48.742+0000] {processor.py:186} INFO - Started process (PID=570) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:26:48.745+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:26:48.748+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:26:48.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:26:48.775+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:26:48.767+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:26:48.778+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:26:48.818+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.086 seconds
[2024-12-30T06:27:19.620+0000] {processor.py:186} INFO - Started process (PID=635) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:27:19.622+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:27:19.625+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:27:19.625+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:27:19.659+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:27:19.650+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:27:19.661+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:27:19.699+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.088 seconds
[2024-12-30T06:27:50.218+0000] {processor.py:186} INFO - Started process (PID=701) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:27:50.220+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:27:50.223+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:27:50.222+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:27:50.259+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:27:50.250+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:27:50.264+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:27:50.332+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.124 seconds
[2024-12-30T06:28:20.631+0000] {processor.py:186} INFO - Started process (PID=767) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:28:20.635+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:28:20.639+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:28:20.637+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:28:20.769+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:28:20.729+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:28:20.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:28:20.948+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.332 seconds
[2024-12-30T06:28:51.723+0000] {processor.py:186} INFO - Started process (PID=832) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:28:51.726+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:28:51.732+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:28:51.732+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:28:51.802+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:28:51.781+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:28:51.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:28:51.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.189 seconds
[2024-12-30T06:29:22.061+0000] {processor.py:186} INFO - Started process (PID=897) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:29:22.063+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:29:22.066+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:29:22.065+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:29:22.111+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:29:22.099+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:29:22.115+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:29:22.156+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.107 seconds
[2024-12-30T06:29:52.846+0000] {processor.py:186} INFO - Started process (PID=963) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:29:52.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:29:52.856+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:29:52.855+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:29:52.907+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:29:52.889+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:29:52.912+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:29:52.965+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.135 seconds
[2024-12-30T06:30:23.879+0000] {processor.py:186} INFO - Started process (PID=1028) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:30:23.881+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:30:23.887+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:30:23.887+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:30:23.978+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:30:23.946+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:30:23.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:30:24.086+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.219 seconds
[2024-12-30T06:30:54.530+0000] {processor.py:186} INFO - Started process (PID=1094) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:30:54.536+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:30:54.564+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:30:54.559+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:30:54.769+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:30:54.719+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:30:54.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:30:55.013+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.550 seconds
[2024-12-30T06:31:25.521+0000] {processor.py:186} INFO - Started process (PID=1166) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:31:25.523+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:31:25.526+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:31:25.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:31:25.559+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:31:25.550+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:31:25.564+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:31:25.608+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.096 seconds
[2024-12-30T06:31:55.782+0000] {processor.py:186} INFO - Started process (PID=1233) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:31:55.784+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:31:55.787+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:31:55.786+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:31:55.811+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:31:55.804+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:31:55.813+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:31:55.844+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.072 seconds
[2024-12-30T06:32:26.251+0000] {processor.py:186} INFO - Started process (PID=1298) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:32:26.252+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:32:26.255+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:32:26.254+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:32:26.284+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:32:26.275+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:32:26.287+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:32:26.316+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.074 seconds
[2024-12-30T06:32:56.877+0000] {processor.py:186} INFO - Started process (PID=1364) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:32:56.879+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:32:56.882+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:32:56.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:32:56.905+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:32:56.898+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:32:56.907+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:32:56.940+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.071 seconds
[2024-12-30T06:33:27.530+0000] {processor.py:186} INFO - Started process (PID=1430) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:33:27.535+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:33:27.542+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:33:27.541+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:33:27.582+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:33:27.569+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:33:27.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:33:27.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.111 seconds
[2024-12-30T06:33:57.761+0000] {processor.py:186} INFO - Started process (PID=1496) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:33:57.762+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:33:57.766+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:33:57.765+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:33:57.815+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:33:57.803+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:33:57.822+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:33:57.870+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.124 seconds
[2024-12-30T06:34:28.035+0000] {processor.py:186} INFO - Started process (PID=1562) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:34:28.040+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:34:28.044+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:34:28.044+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:34:28.082+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:34:28.071+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:34:28.088+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:34:28.129+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.114 seconds
[2024-12-30T06:34:58.447+0000] {processor.py:186} INFO - Started process (PID=1628) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:34:58.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:34:58.451+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:34:58.450+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:34:58.483+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:34:58.476+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:34:58.486+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:34:58.519+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.083 seconds
[2024-12-30T06:35:29.308+0000] {processor.py:186} INFO - Started process (PID=1695) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:35:29.314+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:35:29.318+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:35:29.317+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:35:29.362+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:35:29.351+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:35:29.367+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:35:29.451+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.158 seconds
[2024-12-30T06:36:00.832+0000] {processor.py:186} INFO - Started process (PID=1762) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:36:00.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:36:00.846+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:36:00.842+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:36:01.088+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:36:01.054+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:36:01.107+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:36:01.278+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.530 seconds
[2024-12-30T06:36:31.570+0000] {processor.py:186} INFO - Started process (PID=1828) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:36:31.572+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:36:31.574+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:36:31.574+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:36:31.601+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:36:31.595+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:36:31.604+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:36:31.634+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.077 seconds
[2024-12-30T06:37:02.248+0000] {processor.py:186} INFO - Started process (PID=1893) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:37:02.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:37:02.252+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:37:02.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:37:02.278+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:37:02.271+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:37:02.280+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:37:02.308+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.070 seconds
[2024-12-30T06:37:32.660+0000] {processor.py:186} INFO - Started process (PID=1959) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:37:32.662+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:37:32.666+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:37:32.665+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:37:32.694+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:37:32.686+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:37:32.698+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:37:32.733+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.082 seconds
[2024-12-30T06:38:02.948+0000] {processor.py:186} INFO - Started process (PID=2025) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:38:02.950+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:38:02.953+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:38:02.952+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:38:02.980+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:38:02.973+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:38:02.983+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:38:03.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.080 seconds
[2024-12-30T06:38:33.105+0000] {processor.py:186} INFO - Started process (PID=2091) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:38:33.107+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:38:33.110+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:38:33.109+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:38:33.145+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:38:33.132+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:38:33.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:38:33.179+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.082 seconds
[2024-12-30T06:39:03.540+0000] {processor.py:186} INFO - Started process (PID=2157) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:39:03.543+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:39:03.546+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:39:03.545+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:39:03.572+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:39:03.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:39:03.578+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:39:03.617+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.087 seconds
[2024-12-30T06:39:33.915+0000] {processor.py:186} INFO - Started process (PID=2223) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:39:33.918+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:39:33.921+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:39:33.920+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:39:33.956+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:39:33.945+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:39:33.960+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:39:34.001+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.096 seconds
[2024-12-30T06:40:04.461+0000] {processor.py:186} INFO - Started process (PID=2289) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:40:04.464+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:40:04.466+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:40:04.466+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:40:04.508+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:40:04.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:40:04.515+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:40:04.572+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.120 seconds
[2024-12-30T06:40:34.766+0000] {processor.py:186} INFO - Started process (PID=2355) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:40:34.767+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:40:34.770+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:40:34.770+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:40:34.794+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:40:34.787+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:40:34.797+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:40:34.824+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.069 seconds
[2024-12-30T06:41:05.572+0000] {processor.py:186} INFO - Started process (PID=2421) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:41:05.573+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:41:05.577+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:41:05.576+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:41:05.605+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:41:05.598+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:41:05.611+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:41:05.656+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.092 seconds
[2024-12-30T06:41:36.197+0000] {processor.py:186} INFO - Started process (PID=2487) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:41:36.199+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:41:36.201+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:41:36.201+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:41:36.223+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:41:36.217+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:41:36.225+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:41:36.252+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.063 seconds
[2024-12-30T06:42:07.012+0000] {processor.py:186} INFO - Started process (PID=2553) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:42:07.015+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:42:07.019+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:42:07.018+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:42:07.052+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:42:07.041+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:42:07.057+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:42:07.102+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.105 seconds
[2024-12-30T06:42:37.891+0000] {processor.py:186} INFO - Started process (PID=2619) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:42:37.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:42:37.895+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:42:37.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:42:37.926+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:42:37.919+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:42:37.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:42:37.960+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.080 seconds
[2024-12-30T06:43:08.602+0000] {processor.py:186} INFO - Started process (PID=2685) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:43:08.604+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:43:08.607+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:43:08.606+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:43:08.631+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:43:08.623+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:43:08.633+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:43:08.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.067 seconds
[2024-12-30T06:43:39.143+0000] {processor.py:186} INFO - Started process (PID=2751) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:43:39.144+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:43:39.146+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:43:39.146+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:43:39.175+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:43:39.168+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:43:39.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:43:39.208+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.077 seconds
[2024-12-30T06:44:09.699+0000] {processor.py:186} INFO - Started process (PID=2817) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:44:09.700+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:44:09.702+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:44:09.702+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:44:09.726+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:44:09.718+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:44:09.729+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:44:09.761+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.070 seconds
[2024-12-30T06:44:40.485+0000] {processor.py:186} INFO - Started process (PID=2883) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:44:40.487+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:44:40.490+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:44:40.489+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:44:40.515+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:44:40.507+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:44:40.517+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:44:40.547+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.073 seconds
[2024-12-30T06:45:11.261+0000] {processor.py:186} INFO - Started process (PID=2949) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:45:11.262+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:45:11.267+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:45:11.266+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:45:11.298+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:45:11.291+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:45:11.301+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:45:11.332+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.080 seconds
[2024-12-30T06:45:41.523+0000] {processor.py:186} INFO - Started process (PID=3015) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:45:41.525+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:45:41.527+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:45:41.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:45:41.550+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:45:41.544+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:45:41.554+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:45:41.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.078 seconds
[2024-12-30T06:46:12.431+0000] {processor.py:186} INFO - Started process (PID=3081) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:46:12.433+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:46:12.436+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:46:12.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:46:12.472+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:46:12.461+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:46:12.475+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:46:12.508+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.087 seconds
[2024-12-30T06:46:42.635+0000] {processor.py:186} INFO - Started process (PID=3146) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:46:42.636+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:46:42.639+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:46:42.639+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:46:42.665+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:46:42.658+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:46:42.669+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:46:42.701+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.075 seconds
[2024-12-30T06:47:13.170+0000] {processor.py:186} INFO - Started process (PID=3211) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:47:13.171+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:47:13.174+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:47:13.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:47:13.199+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:47:13.191+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:47:13.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:47:13.234+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.073 seconds
[2024-12-30T06:47:43.599+0000] {processor.py:186} INFO - Started process (PID=3277) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:47:43.603+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:47:43.609+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:47:43.608+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:47:43.656+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:47:43.639+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:47:43.663+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:47:43.705+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.114 seconds
[2024-12-30T06:48:14.505+0000] {processor.py:186} INFO - Started process (PID=3343) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:48:14.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:48:14.510+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:48:14.509+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:48:14.592+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:48:14.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:48:14.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:48:14.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.137 seconds
[2024-12-30T06:48:44.943+0000] {processor.py:186} INFO - Started process (PID=3409) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:48:44.945+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:48:44.947+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:48:44.946+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:48:44.967+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:48:44.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:48:44.970+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:48:44.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.062 seconds
[2024-12-30T06:49:15.709+0000] {processor.py:186} INFO - Started process (PID=3475) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:49:15.713+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:49:15.718+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:49:15.718+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:49:15.750+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:49:15.743+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:49:15.753+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:49:15.796+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.101 seconds
[2024-12-30T06:49:46.074+0000] {processor.py:186} INFO - Started process (PID=3541) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:49:46.075+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:49:46.079+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:49:46.078+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:49:46.102+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:49:46.096+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:49:46.105+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:49:46.132+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.068 seconds
[2024-12-30T06:50:16.367+0000] {processor.py:186} INFO - Started process (PID=3607) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:50:16.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:50:16.372+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:50:16.371+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:50:16.406+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:50:16.395+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:50:16.410+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:50:16.448+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.091 seconds
[2024-12-30T06:50:46.971+0000] {processor.py:186} INFO - Started process (PID=3672) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:50:46.973+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:50:46.976+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:50:46.976+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:50:47.001+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:50:46.994+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:50:47.004+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:50:47.030+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.070 seconds
[2024-12-30T06:51:17.317+0000] {processor.py:186} INFO - Started process (PID=3738) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:51:17.319+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:51:17.322+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:51:17.321+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:51:17.347+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:51:17.339+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:51:17.350+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:51:17.385+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.077 seconds
[2024-12-30T06:51:47.846+0000] {processor.py:186} INFO - Started process (PID=3804) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:51:47.847+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:51:47.849+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:51:47.849+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:51:47.885+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:51:47.877+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:51:47.889+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:51:47.925+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.089 seconds
[2024-12-30T06:52:18.139+0000] {processor.py:186} INFO - Started process (PID=3870) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:52:18.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:52:18.148+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:52:18.147+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:52:18.186+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:52:18.178+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:52:18.190+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:52:18.298+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.181 seconds
[2024-12-30T06:52:48.457+0000] {processor.py:186} INFO - Started process (PID=3937) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:52:48.459+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:52:48.462+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:52:48.461+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:52:48.488+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:52:48.482+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:52:48.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:52:48.526+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.083 seconds
[2024-12-30T06:53:19.272+0000] {processor.py:186} INFO - Started process (PID=4003) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:53:19.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:53:19.276+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:53:19.276+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:53:19.303+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:53:19.295+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:53:19.307+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:53:19.340+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.079 seconds
[2024-12-30T06:53:49.739+0000] {processor.py:186} INFO - Started process (PID=4069) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:53:49.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:53:49.743+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:53:49.742+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:53:49.768+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:53:49.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:53:49.770+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:53:49.804+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.074 seconds
[2024-12-30T06:54:20.619+0000] {processor.py:186} INFO - Started process (PID=4135) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:54:20.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:54:20.623+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:54:20.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:54:20.658+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:54:20.647+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:54:20.660+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:54:20.691+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.087 seconds
[2024-12-30T06:54:51.379+0000] {processor.py:186} INFO - Started process (PID=4201) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:54:51.381+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:54:51.384+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:54:51.383+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:54:51.408+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:54:51.401+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:54:51.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:54:51.442+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.073 seconds
[2024-12-30T06:55:21.775+0000] {processor.py:186} INFO - Started process (PID=4267) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:55:21.777+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:55:21.779+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:55:21.779+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:55:21.805+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:55:21.798+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:55:21.808+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:55:21.846+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.080 seconds
[2024-12-30T06:55:52.218+0000] {processor.py:186} INFO - Started process (PID=4333) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:55:52.220+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:55:52.222+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:55:52.221+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:55:52.253+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:55:52.240+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:55:52.258+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:55:52.296+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.087 seconds
[2024-12-30T06:56:22.741+0000] {processor.py:186} INFO - Started process (PID=4398) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:56:22.744+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:56:22.748+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:56:22.747+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:56:22.787+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:56:22.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:56:22.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:56:22.839+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.114 seconds
[2024-12-30T06:56:53.404+0000] {processor.py:186} INFO - Started process (PID=4464) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:56:53.407+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:56:53.410+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:56:53.410+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:56:53.437+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:56:53.430+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:56:53.444+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:56:53.487+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.096 seconds
[2024-12-30T06:57:23.644+0000] {processor.py:186} INFO - Started process (PID=4530) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:57:23.645+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:57:23.649+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:57:23.648+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:57:23.680+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:57:23.672+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:57:23.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:57:23.722+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.088 seconds
[2024-12-30T06:57:54.690+0000] {processor.py:186} INFO - Started process (PID=4596) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:57:54.692+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:57:54.694+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:57:54.694+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:57:54.719+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:57:54.712+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:57:54.722+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:57:54.751+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.072 seconds
[2024-12-30T06:58:25.119+0000] {processor.py:186} INFO - Started process (PID=4662) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:58:25.121+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:58:25.123+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:58:25.123+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:58:25.159+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:58:25.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:58:25.161+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:58:25.189+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.080 seconds
[2024-12-30T06:58:55.776+0000] {processor.py:186} INFO - Started process (PID=4728) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:58:55.778+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:58:55.780+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:58:55.779+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:58:55.808+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:58:55.799+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:58:55.812+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:58:55.846+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.079 seconds
[2024-12-30T06:59:26.045+0000] {processor.py:186} INFO - Started process (PID=4794) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:59:26.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:59:26.050+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:59:26.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:59:26.078+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:59:26.071+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:59:26.080+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:59:26.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.126 seconds
[2024-12-30T06:59:56.246+0000] {processor.py:186} INFO - Started process (PID=4860) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T06:59:56.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T06:59:56.249+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:59:56.249+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:59:56.277+0000] {logging_mixin.py:190} INFO - [2024-12-30T06:59:56.270+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T06:59:56.280+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T06:59:56.321+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.084 seconds
[2024-12-30T07:00:26.487+0000] {processor.py:186} INFO - Started process (PID=4921) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:00:26.490+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:00:26.496+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:00:26.495+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:00:26.531+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:00:26.522+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:00:26.536+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:00:26.581+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.106 seconds
[2024-12-30T07:00:57.050+0000] {processor.py:186} INFO - Started process (PID=4987) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:00:57.052+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:00:57.055+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:00:57.055+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:00:57.081+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:00:57.075+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:00:57.086+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:00:57.123+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.085 seconds
[2024-12-30T07:01:27.418+0000] {processor.py:186} INFO - Started process (PID=5049) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:01:27.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:01:27.422+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:01:27.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:01:27.492+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:01:27.472+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:01:27.497+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:01:27.542+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.132 seconds
[2024-12-30T07:01:58.004+0000] {processor.py:186} INFO - Started process (PID=5115) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:01:58.007+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:01:58.013+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:01:58.012+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:01:58.058+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:01:58.045+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:01:58.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:01:58.127+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.142 seconds
[2024-12-30T07:02:28.254+0000] {processor.py:186} INFO - Started process (PID=5181) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:02:28.255+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:02:28.258+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:02:28.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:02:28.286+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:02:28.276+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:02:28.293+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:02:28.323+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.082 seconds
[2024-12-30T07:02:58.738+0000] {processor.py:186} INFO - Started process (PID=5247) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:02:58.740+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:02:58.743+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:02:58.743+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:02:58.767+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:02:58.761+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:02:58.770+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:02:58.804+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.076 seconds
[2024-12-30T07:03:29.514+0000] {processor.py:186} INFO - Started process (PID=5313) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:03:29.516+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:03:29.520+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:03:29.519+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:03:29.548+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:03:29.540+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:03:29.551+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:03:29.585+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.080 seconds
[2024-12-30T07:03:59.994+0000] {processor.py:186} INFO - Started process (PID=5379) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:03:59.996+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:03:59.999+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:03:59.999+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:04:00.032+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:04:00.021+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:04:00.037+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:04:00.073+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.090 seconds
[2024-12-30T07:04:30.298+0000] {processor.py:186} INFO - Started process (PID=5439) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:04:30.300+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:04:30.302+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:04:30.301+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:04:30.328+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:04:30.321+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:04:30.331+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:04:30.360+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.072 seconds
[2024-12-30T07:05:00.795+0000] {processor.py:186} INFO - Started process (PID=5505) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:05:00.797+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:05:00.800+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:05:00.799+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:05:00.824+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:05:00.818+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:05:00.826+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:05:00.859+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.075 seconds
[2024-12-30T07:05:31.764+0000] {processor.py:186} INFO - Started process (PID=5571) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:05:31.766+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:05:31.769+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:05:31.769+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:05:31.802+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:05:31.795+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:05:31.806+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:05:31.836+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.081 seconds
[2024-12-30T07:06:02.446+0000] {processor.py:186} INFO - Started process (PID=5637) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:06:02.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:06:02.450+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:06:02.449+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:06:02.481+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:06:02.468+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:06:02.483+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:06:02.521+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.083 seconds
[2024-12-30T07:06:33.443+0000] {processor.py:186} INFO - Started process (PID=5703) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:06:33.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:06:33.447+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:06:33.447+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:06:33.474+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:06:33.468+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:06:33.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:06:33.502+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.067 seconds
[2024-12-30T07:07:03.832+0000] {processor.py:186} INFO - Started process (PID=5769) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:07:03.835+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:07:03.838+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:07:03.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:07:03.873+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:07:03.866+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:07:03.880+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:07:03.922+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.101 seconds
[2024-12-30T07:07:34.108+0000] {processor.py:186} INFO - Started process (PID=5834) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:07:34.110+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:07:34.112+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:07:34.111+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:07:34.150+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:07:34.142+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:07:34.154+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:07:34.195+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.094 seconds
[2024-12-30T07:08:04.620+0000] {processor.py:186} INFO - Started process (PID=5898) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:08:04.621+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:08:04.623+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:08:04.622+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:08:04.654+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:08:04.647+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:08:04.656+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:08:04.705+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.094 seconds
[2024-12-30T07:08:35.680+0000] {processor.py:186} INFO - Started process (PID=5964) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:08:35.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:08:35.686+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:08:35.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:08:35.715+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:08:35.709+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:08:35.717+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:08:35.747+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.080 seconds
[2024-12-30T07:09:06.133+0000] {processor.py:186} INFO - Started process (PID=6028) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:09:06.135+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:09:06.139+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:09:06.138+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:09:06.174+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:09:06.164+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:09:06.178+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:09:06.235+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.114 seconds
[2024-12-30T07:09:37.039+0000] {processor.py:186} INFO - Started process (PID=6092) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:09:37.040+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:09:37.042+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:09:37.041+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:09:37.065+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:09:37.060+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:09:37.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:09:37.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.073 seconds
[2024-12-30T07:10:08.019+0000] {processor.py:186} INFO - Started process (PID=6164) to work on /opt/airflow/dags/soda_checks.py
[2024-12-30T07:10:08.022+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-30T07:10:08.029+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:10:08.028+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:10:08.069+0000] {logging_mixin.py:190} INFO - [2024-12-30T07:10:08.060+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-30T07:10:08.072+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-30T07:10:08.115+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.112 seconds
