[2025-01-07T05:57:38.271+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/soda_checks.py
[2025-01-07T05:57:38.276+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-07T05:57:38.283+0000] {logging_mixin.py:190} INFO - [2025-01-07T05:57:38.283+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-07T05:57:38.320+0000] {logging_mixin.py:190} INFO - [2025-01-07T05:57:38.308+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-07T05:57:38.323+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-07T05:57:38.390+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.207 seconds
[2025-01-07T05:58:10.907+0000] {processor.py:186} INFO - Started process (PID=105) to work on /opt/airflow/dags/soda_checks.py
[2025-01-07T05:58:10.908+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-07T05:58:10.912+0000] {logging_mixin.py:190} INFO - [2025-01-07T05:58:10.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-07T05:58:10.933+0000] {logging_mixin.py:190} INFO - [2025-01-07T05:58:10.928+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-07T05:58:10.935+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-07T05:58:10.961+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.061 seconds
[2025-01-07T05:58:41.655+0000] {processor.py:186} INFO - Started process (PID=171) to work on /opt/airflow/dags/soda_checks.py
[2025-01-07T05:58:41.656+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-07T05:58:41.660+0000] {logging_mixin.py:190} INFO - [2025-01-07T05:58:41.660+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-07T05:58:41.692+0000] {logging_mixin.py:190} INFO - [2025-01-07T05:58:41.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-07T05:58:41.694+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-07T05:58:41.729+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.082 seconds
[2025-01-07T05:59:12.638+0000] {processor.py:186} INFO - Started process (PID=237) to work on /opt/airflow/dags/soda_checks.py
[2025-01-07T05:59:12.640+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-07T05:59:12.644+0000] {logging_mixin.py:190} INFO - [2025-01-07T05:59:12.644+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-07T05:59:12.673+0000] {logging_mixin.py:190} INFO - [2025-01-07T05:59:12.665+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-07T05:59:12.676+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-07T05:59:12.724+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.094 seconds
[2025-01-07T05:59:43.288+0000] {processor.py:186} INFO - Started process (PID=304) to work on /opt/airflow/dags/soda_checks.py
[2025-01-07T05:59:43.290+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-07T05:59:43.293+0000] {logging_mixin.py:190} INFO - [2025-01-07T05:59:43.293+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-07T05:59:43.318+0000] {logging_mixin.py:190} INFO - [2025-01-07T05:59:43.313+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-07T05:59:43.321+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-07T05:59:43.351+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.070 seconds
[2025-01-07T06:00:13.837+0000] {processor.py:186} INFO - Started process (PID=370) to work on /opt/airflow/dags/soda_checks.py
[2025-01-07T06:00:13.840+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-07T06:00:13.849+0000] {logging_mixin.py:190} INFO - [2025-01-07T06:00:13.848+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-07T06:00:13.892+0000] {logging_mixin.py:190} INFO - [2025-01-07T06:00:13.883+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-07T06:00:13.899+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-07T06:00:13.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.129 seconds
[2025-01-07T06:00:44.435+0000] {processor.py:186} INFO - Started process (PID=436) to work on /opt/airflow/dags/soda_checks.py
[2025-01-07T06:00:44.437+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-07T06:00:44.443+0000] {logging_mixin.py:190} INFO - [2025-01-07T06:00:44.442+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-07T06:00:44.477+0000] {logging_mixin.py:190} INFO - [2025-01-07T06:00:44.471+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-07T06:00:44.479+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-07T06:00:44.524+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.099 seconds
[2025-01-07T06:01:15.058+0000] {processor.py:186} INFO - Started process (PID=502) to work on /opt/airflow/dags/soda_checks.py
[2025-01-07T06:01:15.064+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-07T06:01:15.071+0000] {logging_mixin.py:190} INFO - [2025-01-07T06:01:15.071+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-07T06:01:15.105+0000] {logging_mixin.py:190} INFO - [2025-01-07T06:01:15.096+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-07T06:01:15.108+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-07T06:01:15.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.107 seconds
[2025-01-07T06:01:46.144+0000] {processor.py:186} INFO - Started process (PID=568) to work on /opt/airflow/dags/soda_checks.py
[2025-01-07T06:01:46.147+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-07T06:01:46.151+0000] {logging_mixin.py:190} INFO - [2025-01-07T06:01:46.150+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-07T06:01:46.177+0000] {logging_mixin.py:190} INFO - [2025-01-07T06:01:46.169+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-07T06:01:46.180+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-07T06:01:46.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.092 seconds
[2025-01-07T06:02:16.558+0000] {processor.py:186} INFO - Started process (PID=634) to work on /opt/airflow/dags/soda_checks.py
[2025-01-07T06:02:16.561+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-07T06:02:16.565+0000] {logging_mixin.py:190} INFO - [2025-01-07T06:02:16.565+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-07T06:02:16.585+0000] {logging_mixin.py:190} INFO - [2025-01-07T06:02:16.580+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-07T06:02:16.587+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-07T06:02:16.612+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.061 seconds
[2025-01-07T06:02:46.788+0000] {processor.py:186} INFO - Started process (PID=700) to work on /opt/airflow/dags/soda_checks.py
[2025-01-07T06:02:46.790+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-07T06:02:46.794+0000] {logging_mixin.py:190} INFO - [2025-01-07T06:02:46.794+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-07T06:02:46.815+0000] {logging_mixin.py:190} INFO - [2025-01-07T06:02:46.808+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-07T06:02:46.817+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-07T06:02:46.845+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.063 seconds
[2025-01-07T06:03:17.115+0000] {processor.py:186} INFO - Started process (PID=765) to work on /opt/airflow/dags/soda_checks.py
[2025-01-07T06:03:17.117+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-07T06:03:17.121+0000] {logging_mixin.py:190} INFO - [2025-01-07T06:03:17.120+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-07T06:03:17.146+0000] {logging_mixin.py:190} INFO - [2025-01-07T06:03:17.140+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-07T06:03:17.149+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-07T06:03:17.173+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.066 seconds
[2025-01-07T06:03:48.163+0000] {processor.py:186} INFO - Started process (PID=831) to work on /opt/airflow/dags/soda_checks.py
[2025-01-07T06:03:48.166+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-07T06:03:48.180+0000] {logging_mixin.py:190} INFO - [2025-01-07T06:03:48.179+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-07T06:03:48.260+0000] {logging_mixin.py:190} INFO - [2025-01-07T06:03:48.245+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-07T06:03:48.266+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-07T06:03:48.333+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.194 seconds
