[2024-12-24T07:28:47.229+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:28:47.238+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:28:47.252+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:28:47.250+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:28:47.330+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:28:47.312+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:28:47.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:28:47.435+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.239 seconds
[2024-12-24T07:29:23.072+0000] {processor.py:186} INFO - Started process (PID=105) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:29:23.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:29:23.078+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:29:23.077+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:29:23.117+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:29:23.108+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:29:23.120+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:29:23.149+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.087 seconds
[2024-12-24T07:29:54.201+0000] {processor.py:186} INFO - Started process (PID=171) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:29:54.203+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:29:54.207+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:29:54.206+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:29:54.232+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:29:54.226+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:29:54.234+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:29:54.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.071 seconds
[2024-12-24T07:30:24.517+0000] {processor.py:186} INFO - Started process (PID=237) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:30:24.521+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:30:24.527+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:30:24.526+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:30:24.583+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:30:24.569+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:30:24.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:30:24.673+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.180 seconds
[2024-12-24T07:30:55.043+0000] {processor.py:186} INFO - Started process (PID=303) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:30:55.045+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:30:55.051+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:30:55.050+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:30:55.092+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:30:55.076+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:30:55.094+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:30:55.150+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.126 seconds
[2024-12-24T07:31:25.892+0000] {processor.py:186} INFO - Started process (PID=368) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:31:25.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:31:25.898+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:31:25.897+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:31:25.945+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:31:25.931+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:31:25.956+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:31:26.007+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.127 seconds
[2024-12-24T07:31:56.615+0000] {processor.py:186} INFO - Started process (PID=434) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:31:56.618+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:31:56.622+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:31:56.622+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:31:56.654+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:31:56.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:31:56.657+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:31:56.702+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.094 seconds
[2024-12-24T07:32:27.806+0000] {processor.py:186} INFO - Started process (PID=500) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:32:27.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:32:27.830+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:32:27.828+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:32:27.896+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:32:27.878+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:32:27.904+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:32:27.985+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.206 seconds
[2024-12-24T07:32:58.640+0000] {processor.py:186} INFO - Started process (PID=566) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:32:58.642+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:32:58.647+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:32:58.647+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:32:58.698+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:32:58.685+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:32:58.705+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:32:58.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.144 seconds
[2024-12-24T07:33:29.183+0000] {processor.py:186} INFO - Started process (PID=632) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:33:29.192+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:33:29.197+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:33:29.196+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:33:29.234+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:33:29.226+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:33:29.236+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:33:29.267+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.092 seconds
[2024-12-24T07:33:59.380+0000] {processor.py:186} INFO - Started process (PID=698) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:33:59.382+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:33:59.385+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:33:59.385+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:33:59.428+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:33:59.423+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:33:59.430+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:33:59.460+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.089 seconds
[2024-12-24T07:34:29.615+0000] {processor.py:186} INFO - Started process (PID=765) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:34:29.617+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:34:29.623+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:34:29.621+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:34:29.652+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:34:29.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:34:29.654+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:34:29.683+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.076 seconds
[2024-12-24T07:35:00.226+0000] {processor.py:186} INFO - Started process (PID=831) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:35:00.228+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:35:00.236+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:35:00.236+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:35:00.276+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:35:00.263+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:35:00.278+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:35:00.334+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.122 seconds
[2024-12-24T07:35:31.309+0000] {processor.py:186} INFO - Started process (PID=897) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:35:31.311+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:35:31.318+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:35:31.317+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:35:31.348+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:35:31.341+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:35:31.351+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:35:31.390+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.091 seconds
[2024-12-24T07:36:02.387+0000] {processor.py:186} INFO - Started process (PID=963) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:36:02.388+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:36:02.393+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:36:02.392+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:36:02.433+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:36:02.425+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:36:02.435+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:36:02.472+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.094 seconds
[2024-12-24T07:36:33.166+0000] {processor.py:186} INFO - Started process (PID=1029) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:36:33.171+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:36:33.186+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:36:33.186+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:36:33.234+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:36:33.220+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:36:33.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:36:33.302+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.154 seconds
[2024-12-24T07:37:04.008+0000] {processor.py:186} INFO - Started process (PID=1095) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:37:04.010+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:37:04.014+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:37:04.014+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:37:04.042+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:37:04.035+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:37:04.045+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:37:04.081+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.082 seconds
[2024-12-24T07:37:34.426+0000] {processor.py:186} INFO - Started process (PID=1162) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:37:34.428+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:37:34.432+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:37:34.432+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:37:34.463+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:37:34.454+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:37:34.465+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:37:34.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.079 seconds
[2024-12-24T07:38:04.849+0000] {processor.py:186} INFO - Started process (PID=1228) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:38:04.853+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:38:04.867+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:38:04.865+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:38:04.925+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:38:04.914+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:38:04.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:38:04.994+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.159 seconds
[2024-12-24T07:38:35.196+0000] {processor.py:186} INFO - Started process (PID=1293) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:38:35.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:38:35.215+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:38:35.212+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:38:35.277+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:38:35.264+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:38:35.281+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:38:35.332+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.161 seconds
[2024-12-24T07:39:05.417+0000] {processor.py:186} INFO - Started process (PID=1359) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:39:05.420+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:39:05.425+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:39:05.425+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:39:05.450+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:39:05.443+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:39:05.457+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:39:05.495+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.093 seconds
[2024-12-24T07:39:36.432+0000] {processor.py:186} INFO - Started process (PID=1425) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:39:36.434+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:39:36.439+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:39:36.438+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:39:36.464+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:39:36.459+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:39:36.466+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:39:36.492+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.068 seconds
[2024-12-24T07:40:06.985+0000] {processor.py:186} INFO - Started process (PID=1491) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:40:06.986+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:40:06.989+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:40:06.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:40:07.016+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:40:07.009+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:40:07.019+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:40:07.052+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.080 seconds
[2024-12-24T07:40:38.096+0000] {processor.py:186} INFO - Started process (PID=1557) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:40:38.097+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:40:38.099+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:40:38.099+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:40:38.120+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:40:38.115+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:40:38.122+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:40:38.148+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.059 seconds
[2024-12-24T07:41:08.340+0000] {processor.py:186} INFO - Started process (PID=1623) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:41:08.341+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:41:08.344+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:41:08.343+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:41:08.371+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:41:08.366+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:41:08.373+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:41:08.398+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.065 seconds
[2024-12-24T07:41:38.645+0000] {processor.py:186} INFO - Started process (PID=1690) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:41:38.651+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:41:38.659+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:41:38.656+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:41:38.697+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:41:38.688+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:41:38.702+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:41:38.767+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.143 seconds
[2024-12-24T07:42:08.953+0000] {processor.py:186} INFO - Started process (PID=1758) to work on /opt/airflow/dags/soda_checks.py
[2024-12-24T07:42:08.955+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2024-12-24T07:42:08.957+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:42:08.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:42:08.988+0000] {logging_mixin.py:190} INFO - [2024-12-24T07:42:08.978+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 12, in <module>
    @task.external_python(python='/usr/local/airflow/soda_venv/bin/python')
     ^^^^
NameError: name 'task' is not defined
[2024-12-24T07:42:08.991+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2024-12-24T07:42:09.018+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.074 seconds
