[2025-01-09T05:01:23.458+0000] {processor.py:186} INFO - Started process (PID=40) to work on /opt/airflow/dags/create_container.py
[2025-01-09T05:01:23.462+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_container.py for tasks to queue
[2025-01-09T05:01:23.475+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:01:23.473+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_container.py
[2025-01-09T05:01:24.093+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:01:24.065+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_container.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_container.py", line 15, in <module>
    import local_to_gcs
  File "/opt/airflow/dags/local_to_gcs.py", line 66, in <module>
    retail_dag = retail()  # Instantiate the DAG
                 ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/local_to_gcs.py", line 31, in retail
    csv_files = [f for f in os.listdir(dataset_folder) if f.endswith(".csv")]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'include/dataset/'
[2025-01-09T05:01:24.095+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_container.py
[2025-01-09T05:01:24.296+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_container.py took 0.856 seconds
[2025-01-09T05:01:54.377+0000] {processor.py:186} INFO - Started process (PID=108) to work on /opt/airflow/dags/create_container.py
[2025-01-09T05:01:54.378+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_container.py for tasks to queue
[2025-01-09T05:01:54.383+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:01:54.382+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_container.py
[2025-01-09T05:01:54.463+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:01:54.440+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_container.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_container.py", line 15, in <module>
    import local_to_gcs
  File "/opt/airflow/dags/local_to_gcs.py", line 66, in <module>
    retail_dag = retail()  # Instantiate the DAG
                 ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/local_to_gcs.py", line 31, in retail
    csv_files = [f for f in os.listdir(dataset_folder) if f.endswith(".csv")]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'include/dataset/'
[2025-01-09T05:01:54.465+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_container.py
[2025-01-09T05:01:54.506+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_container.py took 0.140 seconds
[2025-01-09T05:02:25.024+0000] {processor.py:186} INFO - Started process (PID=174) to work on /opt/airflow/dags/create_container.py
[2025-01-09T05:02:25.026+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_container.py for tasks to queue
[2025-01-09T05:02:25.031+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:02:25.031+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_container.py
[2025-01-09T05:02:25.084+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:02:25.073+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_container.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_container.py", line 15, in <module>
    import local_to_gcs
  File "/opt/airflow/dags/local_to_gcs.py", line 66, in <module>
    retail_dag = retail()  # Instantiate the DAG
                 ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/local_to_gcs.py", line 31, in retail
    csv_files = [f for f in os.listdir(dataset_folder) if f.endswith(".csv")]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'include/dataset/'
[2025-01-09T05:02:25.086+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_container.py
[2025-01-09T05:02:25.114+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_container.py took 0.099 seconds
[2025-01-09T05:02:55.927+0000] {processor.py:186} INFO - Started process (PID=241) to work on /opt/airflow/dags/create_container.py
[2025-01-09T05:02:55.929+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_container.py for tasks to queue
[2025-01-09T05:02:55.933+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:02:55.933+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_container.py
[2025-01-09T05:02:55.985+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:02:55.970+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_container.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_container.py", line 15, in <module>
    import local_to_gcs
  File "/opt/airflow/dags/local_to_gcs.py", line 66, in <module>
    retail_dag = retail()  # Instantiate the DAG
                 ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/local_to_gcs.py", line 31, in retail
    csv_files = [f for f in os.listdir(dataset_folder) if f.endswith(".csv")]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'include/dataset/'
[2025-01-09T05:02:55.987+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_container.py
[2025-01-09T05:02:56.012+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_container.py took 0.093 seconds
[2025-01-09T05:03:26.465+0000] {processor.py:186} INFO - Started process (PID=308) to work on /opt/airflow/dags/create_container.py
[2025-01-09T05:03:26.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_container.py for tasks to queue
[2025-01-09T05:03:26.486+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:03:26.484+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_container.py
[2025-01-09T05:03:26.609+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:03:26.576+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_container.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_container.py", line 15, in <module>
    import local_to_gcs
  File "/opt/airflow/dags/local_to_gcs.py", line 66, in <module>
    retail_dag = retail()  # Instantiate the DAG
                 ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/local_to_gcs.py", line 31, in retail
    csv_files = [f for f in os.listdir(dataset_folder) if f.endswith(".csv")]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'include/dataset/'
[2025-01-09T05:03:26.617+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_container.py
[2025-01-09T05:03:26.707+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_container.py took 0.271 seconds
[2025-01-09T05:03:56.891+0000] {processor.py:186} INFO - Started process (PID=375) to work on /opt/airflow/dags/create_container.py
[2025-01-09T05:03:56.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_container.py for tasks to queue
[2025-01-09T05:03:56.896+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:03:56.896+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_container.py
[2025-01-09T05:03:56.954+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:03:56.942+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_container.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_container.py", line 15, in <module>
    import local_to_gcs
  File "/opt/airflow/dags/local_to_gcs.py", line 66, in <module>
    retail_dag = retail()  # Instantiate the DAG
                 ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/local_to_gcs.py", line 31, in retail
    csv_files = [f for f in os.listdir(dataset_folder) if f.endswith(".csv")]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'include/dataset/'
[2025-01-09T05:03:56.955+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_container.py
[2025-01-09T05:03:56.981+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_container.py took 0.099 seconds
[2025-01-09T05:04:27.879+0000] {processor.py:186} INFO - Started process (PID=442) to work on /opt/airflow/dags/create_container.py
[2025-01-09T05:04:27.880+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_container.py for tasks to queue
[2025-01-09T05:04:27.884+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:04:27.883+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_container.py
[2025-01-09T05:04:27.935+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:04:27.925+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_container.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_container.py", line 15, in <module>
    import local_to_gcs
  File "/opt/airflow/dags/local_to_gcs.py", line 66, in <module>
    retail_dag = retail()  # Instantiate the DAG
                 ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/local_to_gcs.py", line 31, in retail
    csv_files = [f for f in os.listdir(dataset_folder) if f.endswith(".csv")]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'include/dataset/'
[2025-01-09T05:04:27.937+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_container.py
[2025-01-09T05:04:27.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_container.py took 0.091 seconds
[2025-01-09T05:04:58.434+0000] {processor.py:186} INFO - Started process (PID=509) to work on /opt/airflow/dags/create_container.py
[2025-01-09T05:04:58.436+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_container.py for tasks to queue
[2025-01-09T05:04:58.440+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:04:58.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_container.py
[2025-01-09T05:04:58.490+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:04:58.480+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_container.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_container.py", line 15, in <module>
    import local_to_gcs
  File "/opt/airflow/dags/local_to_gcs.py", line 66, in <module>
    retail_dag = retail()  # Instantiate the DAG
                 ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/local_to_gcs.py", line 31, in retail
    csv_files = [f for f in os.listdir(dataset_folder) if f.endswith(".csv")]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'include/dataset/'
[2025-01-09T05:04:58.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_container.py
[2025-01-09T05:04:58.516+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_container.py took 0.090 seconds
[2025-01-09T05:05:29.169+0000] {processor.py:186} INFO - Started process (PID=576) to work on /opt/airflow/dags/create_container.py
[2025-01-09T05:05:29.170+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_container.py for tasks to queue
[2025-01-09T05:05:29.174+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:05:29.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_container.py
[2025-01-09T05:05:29.225+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:05:29.215+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_container.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_container.py", line 15, in <module>
    import local_to_gcs
  File "/opt/airflow/dags/local_to_gcs.py", line 66, in <module>
    retail_dag = retail()  # Instantiate the DAG
                 ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/local_to_gcs.py", line 31, in retail
    csv_files = [f for f in os.listdir(dataset_folder) if f.endswith(".csv")]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'include/dataset/'
[2025-01-09T05:05:29.227+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_container.py
[2025-01-09T05:05:29.253+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_container.py took 0.091 seconds
[2025-01-09T05:05:59.566+0000] {processor.py:186} INFO - Started process (PID=643) to work on /opt/airflow/dags/create_container.py
[2025-01-09T05:05:59.568+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_container.py for tasks to queue
[2025-01-09T05:05:59.571+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:05:59.571+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_container.py
[2025-01-09T05:05:59.623+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:05:59.613+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_container.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_container.py", line 15, in <module>
    import local_to_gcs
  File "/opt/airflow/dags/local_to_gcs.py", line 66, in <module>
    retail_dag = retail()  # Instantiate the DAG
                 ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/local_to_gcs.py", line 31, in retail
    csv_files = [f for f in os.listdir(dataset_folder) if f.endswith(".csv")]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'include/dataset/'
[2025-01-09T05:05:59.624+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_container.py
[2025-01-09T05:05:59.650+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_container.py took 0.092 seconds
[2025-01-09T05:06:30.097+0000] {processor.py:186} INFO - Started process (PID=710) to work on /opt/airflow/dags/create_container.py
[2025-01-09T05:06:30.100+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_container.py for tasks to queue
[2025-01-09T05:06:30.105+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:06:30.104+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_container.py
[2025-01-09T05:06:30.183+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:06:30.166+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_container.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_container.py", line 15, in <module>
    import local_to_gcs
  File "/opt/airflow/dags/local_to_gcs.py", line 66, in <module>
    retail_dag = retail()  # Instantiate the DAG
                 ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/local_to_gcs.py", line 31, in retail
    csv_files = [f for f in os.listdir(dataset_folder) if f.endswith(".csv")]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'include/dataset/'
[2025-01-09T05:06:30.185+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_container.py
[2025-01-09T05:06:30.228+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_container.py took 0.145 seconds
[2025-01-09T05:07:01.182+0000] {processor.py:186} INFO - Started process (PID=777) to work on /opt/airflow/dags/create_container.py
[2025-01-09T05:07:01.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/create_container.py for tasks to queue
[2025-01-09T05:07:01.193+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:07:01.192+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/create_container.py
[2025-01-09T05:07:01.282+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:07:01.261+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/create_container.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/create_container.py", line 15, in <module>
    import local_to_gcs
  File "/opt/airflow/dags/local_to_gcs.py", line 66, in <module>
    retail_dag = retail()  # Instantiate the DAG
                 ^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dag.py", line 4307, in factory
    f(**f_kwargs)
  File "/opt/airflow/dags/local_to_gcs.py", line 31, in retail
    csv_files = [f for f in os.listdir(dataset_folder) if f.endswith(".csv")]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'include/dataset/'
[2025-01-09T05:07:01.286+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/create_container.py
[2025-01-09T05:07:01.332+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/create_container.py took 0.174 seconds
