[2025-01-09T05:01:23.585+0000] {processor.py:186} INFO - Started process (PID=41) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:01:23.590+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:01:23.602+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:01:23.601+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:01:23.670+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:01:23.653+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:01:23.675+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:01:23.773+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.214 seconds
[2025-01-09T05:01:54.267+0000] {processor.py:186} INFO - Started process (PID=107) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:01:54.269+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:01:54.274+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:01:54.273+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:01:54.303+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:01:54.297+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:01:54.305+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:01:54.331+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.073 seconds
[2025-01-09T05:02:25.039+0000] {processor.py:186} INFO - Started process (PID=175) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:02:25.041+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:02:25.045+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:02:25.045+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:02:25.068+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:02:25.061+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:02:25.070+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:02:25.101+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.070 seconds
[2025-01-09T05:02:55.942+0000] {processor.py:186} INFO - Started process (PID=242) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:02:55.944+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:02:55.948+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:02:55.947+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:02:55.971+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:02:55.964+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:02:55.974+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:02:56.006+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.073 seconds
[2025-01-09T05:03:26.518+0000] {processor.py:186} INFO - Started process (PID=309) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:03:26.524+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:03:26.539+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:03:26.539+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:03:26.601+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:03:26.576+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:03:26.605+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:03:26.708+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.232 seconds
[2025-01-09T05:03:56.901+0000] {processor.py:186} INFO - Started process (PID=376) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:03:56.903+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:03:56.907+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:03:56.907+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:03:56.934+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:03:56.927+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:03:56.937+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:03:56.968+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.075 seconds
[2025-01-09T05:04:27.888+0000] {processor.py:186} INFO - Started process (PID=443) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:04:27.890+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:04:27.895+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:04:27.894+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:04:27.917+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:04:27.912+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:04:27.919+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:04:27.947+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.068 seconds
[2025-01-09T05:04:58.447+0000] {processor.py:186} INFO - Started process (PID=510) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:04:58.448+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:04:58.453+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:04:58.452+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:04:58.475+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:04:58.469+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:04:58.477+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:04:58.505+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.068 seconds
[2025-01-09T05:05:29.180+0000] {processor.py:186} INFO - Started process (PID=577) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:05:29.182+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:05:29.186+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:05:29.186+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:05:29.207+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:05:29.202+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:05:29.210+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:05:29.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.067 seconds
[2025-01-09T05:05:59.577+0000] {processor.py:186} INFO - Started process (PID=644) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:05:59.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:05:59.584+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:05:59.583+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:05:59.605+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:05:59.600+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:05:59.608+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:05:59.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.067 seconds
[2025-01-09T05:06:30.115+0000] {processor.py:186} INFO - Started process (PID=711) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:06:30.118+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:06:30.124+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:06:30.124+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:06:30.160+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:06:30.147+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:06:30.165+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:06:30.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.111 seconds
[2025-01-09T05:07:01.182+0000] {processor.py:186} INFO - Started process (PID=778) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:07:01.185+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:07:01.193+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:07:01.192+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:07:01.237+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:07:01.228+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:07:01.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:07:01.305+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.138 seconds
[2025-01-09T05:07:32.403+0000] {processor.py:186} INFO - Started process (PID=844) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:07:32.404+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:07:32.407+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:07:32.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:07:32.462+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:07:32.449+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:07:32.470+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:07:32.522+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.132 seconds
[2025-01-09T05:08:03.163+0000] {processor.py:186} INFO - Started process (PID=909) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:08:03.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:08:03.167+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:08:03.167+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:08:03.195+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:08:03.189+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:08:03.198+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:08:03.231+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.093 seconds
[2025-01-09T05:08:33.951+0000] {processor.py:186} INFO - Started process (PID=974) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:08:33.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:08:33.956+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:08:33.955+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:08:34.024+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:08:34.003+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:08:34.028+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:08:34.096+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.163 seconds
[2025-01-09T05:09:04.433+0000] {processor.py:186} INFO - Started process (PID=1040) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:09:04.435+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:09:04.438+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:09:04.437+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:09:04.472+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:09:04.460+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:09:04.476+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:09:04.514+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.092 seconds
[2025-01-09T05:09:35.159+0000] {processor.py:186} INFO - Started process (PID=1105) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:09:35.162+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:09:35.166+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:09:35.165+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:09:35.215+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:09:35.200+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:09:35.220+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:09:35.263+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.115 seconds
[2025-01-09T05:10:05.668+0000] {processor.py:186} INFO - Started process (PID=1171) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:10:05.671+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:10:05.675+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:10:05.674+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:10:05.721+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:10:05.707+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:10:05.725+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:10:05.781+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.127 seconds
[2025-01-09T05:10:36.383+0000] {processor.py:186} INFO - Started process (PID=1237) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:10:36.385+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:10:36.388+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:10:36.388+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:10:36.427+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:10:36.414+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:10:36.430+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:10:36.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.108 seconds
[2025-01-09T05:11:06.547+0000] {processor.py:186} INFO - Started process (PID=1303) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:11:06.549+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:11:06.551+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:11:06.550+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:11:06.577+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:11:06.571+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:11:06.579+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:11:06.608+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.068 seconds
[2025-01-09T05:11:37.198+0000] {processor.py:186} INFO - Started process (PID=1369) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:11:37.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:11:37.203+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:11:37.202+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:11:37.292+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:11:37.283+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:11:37.295+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:11:37.353+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.163 seconds
[2025-01-09T05:12:07.777+0000] {processor.py:186} INFO - Started process (PID=1441) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:12:07.781+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:12:07.784+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:12:07.784+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:12:07.828+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:12:07.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:12:07.834+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:12:07.885+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.123 seconds
[2025-01-09T05:12:38.831+0000] {processor.py:186} INFO - Started process (PID=1507) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:12:38.834+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:12:38.837+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:12:38.837+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:12:38.875+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:12:38.865+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:12:38.879+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:12:38.928+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.158 seconds
[2025-01-09T05:13:09.481+0000] {processor.py:186} INFO - Started process (PID=1573) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:13:09.483+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:13:09.486+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:13:09.486+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:13:09.520+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:13:09.508+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:13:09.525+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:13:09.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.102 seconds
[2025-01-09T05:13:39.959+0000] {processor.py:186} INFO - Started process (PID=1639) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:13:39.962+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:13:39.964+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:13:39.964+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:13:39.998+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:13:39.990+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:13:40.001+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:13:40.034+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.086 seconds
[2025-01-09T05:14:10.174+0000] {processor.py:186} INFO - Started process (PID=1705) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:14:10.175+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:14:10.177+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:14:10.176+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:14:10.208+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:14:10.201+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:14:10.210+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:14:10.240+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.075 seconds
[2025-01-09T05:14:41.161+0000] {processor.py:186} INFO - Started process (PID=1770) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:14:41.164+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:14:41.168+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:14:41.167+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:14:41.200+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:14:41.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:14:41.202+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:14:41.242+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.090 seconds
[2025-01-09T05:15:11.525+0000] {processor.py:186} INFO - Started process (PID=1836) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:15:11.527+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:15:11.529+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:15:11.529+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:15:11.557+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:15:11.551+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:15:11.560+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:15:11.594+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.080 seconds
[2025-01-09T05:15:41.658+0000] {processor.py:186} INFO - Started process (PID=1902) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:15:41.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:15:41.662+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:15:41.661+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:15:41.697+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:15:41.691+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:15:41.700+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:15:41.745+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.096 seconds
[2025-01-09T05:16:12.076+0000] {processor.py:186} INFO - Started process (PID=1968) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:16:12.079+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:16:12.081+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:16:12.081+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:16:12.141+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:16:12.130+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:16:12.148+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:16:12.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.154 seconds
[2025-01-09T05:16:42.711+0000] {processor.py:186} INFO - Started process (PID=2033) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:16:42.714+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:16:42.718+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:16:42.717+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:16:42.751+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:16:42.742+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:16:42.754+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:16:42.800+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.114 seconds
[2025-01-09T05:17:13.086+0000] {processor.py:186} INFO - Started process (PID=2099) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:17:13.087+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:17:13.092+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:17:13.091+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:17:13.120+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:17:13.111+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:17:13.125+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:17:13.161+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.083 seconds
[2025-01-09T05:17:43.687+0000] {processor.py:186} INFO - Started process (PID=2165) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:17:43.688+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:17:43.690+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:17:43.690+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:17:43.722+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:17:43.713+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:17:43.726+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:17:43.764+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.086 seconds
[2025-01-09T05:18:14.158+0000] {processor.py:186} INFO - Started process (PID=2232) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:18:14.160+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:18:14.164+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:18:14.164+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:18:14.199+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:18:14.193+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:18:14.203+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:18:14.272+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.127 seconds
[2025-01-09T05:18:44.963+0000] {processor.py:186} INFO - Started process (PID=2298) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:18:44.965+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:18:44.967+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:18:44.967+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:18:45.003+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:18:44.994+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:18:45.006+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:18:45.048+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.099 seconds
[2025-01-09T05:19:15.991+0000] {processor.py:186} INFO - Started process (PID=2364) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:19:15.993+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:19:15.995+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:19:15.994+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:19:16.030+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:19:16.022+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:19:16.033+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:19:16.074+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.092 seconds
[2025-01-09T05:19:46.154+0000] {processor.py:186} INFO - Started process (PID=2431) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:19:46.156+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:19:46.158+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:19:46.157+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:19:46.188+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:19:46.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:19:46.192+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:19:46.222+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.076 seconds
[2025-01-09T05:20:16.445+0000] {processor.py:186} INFO - Started process (PID=2497) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:20:16.447+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:20:16.449+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:20:16.448+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:20:16.486+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:20:16.478+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:20:16.488+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:20:16.525+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.090 seconds
[2025-01-09T05:20:46.844+0000] {processor.py:186} INFO - Started process (PID=2563) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:20:46.846+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:20:46.848+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:20:46.848+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:20:46.883+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:20:46.874+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:20:46.885+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:20:46.923+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.086 seconds
[2025-01-09T05:21:17.166+0000] {processor.py:186} INFO - Started process (PID=2628) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:21:17.167+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:21:17.169+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:21:17.169+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:21:17.203+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:21:17.195+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:21:17.208+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:21:17.250+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.095 seconds
[2025-01-09T05:21:48.131+0000] {processor.py:186} INFO - Started process (PID=2695) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:21:48.132+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:21:48.136+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:21:48.136+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:21:48.175+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:21:48.163+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:21:48.179+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:21:48.219+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.099 seconds
[2025-01-09T05:22:19.233+0000] {processor.py:186} INFO - Started process (PID=2761) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:22:19.235+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:22:19.237+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:22:19.237+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:22:19.281+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:22:19.271+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:22:19.283+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:22:19.323+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.103 seconds
[2025-01-09T05:22:50.062+0000] {processor.py:186} INFO - Started process (PID=2827) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:22:50.067+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:22:50.072+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:22:50.070+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:22:50.106+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:22:50.099+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:22:50.109+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:22:50.172+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.134 seconds
[2025-01-09T05:23:20.977+0000] {processor.py:186} INFO - Started process (PID=2893) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:23:20.979+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:23:20.981+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:23:20.980+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:23:21.009+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:23:21.002+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:23:21.012+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:23:21.046+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.078 seconds
[2025-01-09T05:23:51.184+0000] {processor.py:186} INFO - Started process (PID=2959) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:23:51.187+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:23:51.189+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:23:51.189+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:23:51.226+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:23:51.216+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:23:51.228+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:23:51.262+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.086 seconds
[2025-01-09T05:24:21.357+0000] {processor.py:186} INFO - Started process (PID=3024) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:24:21.358+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:24:21.362+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:24:21.362+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:24:21.391+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:24:21.384+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:24:21.395+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:24:21.432+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.083 seconds
[2025-01-09T05:24:52.190+0000] {processor.py:186} INFO - Started process (PID=3090) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:24:52.192+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:24:52.195+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:24:52.194+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:24:52.235+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:24:52.224+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:24:52.238+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:24:52.275+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.095 seconds
[2025-01-09T05:25:22.697+0000] {processor.py:186} INFO - Started process (PID=3157) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:25:22.698+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:25:22.702+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:25:22.702+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:25:22.732+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:25:22.725+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:25:22.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:25:22.766+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.078 seconds
[2025-01-09T05:25:53.002+0000] {processor.py:186} INFO - Started process (PID=3223) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:25:53.004+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:25:53.009+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:25:53.008+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:25:53.044+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:25:53.036+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:25:53.047+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:25:53.085+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.092 seconds
[2025-01-09T05:26:23.877+0000] {processor.py:186} INFO - Started process (PID=3289) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:26:23.878+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:26:23.880+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:26:23.880+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:26:23.905+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:26:23.898+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:26:23.907+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:26:23.945+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.078 seconds
[2025-01-09T05:26:54.965+0000] {processor.py:186} INFO - Started process (PID=3355) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:26:54.967+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:26:54.969+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:26:54.969+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:26:55.004+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:26:54.994+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:26:55.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:26:55.045+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.089 seconds
[2025-01-09T05:27:25.125+0000] {processor.py:186} INFO - Started process (PID=3421) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:27:25.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:27:25.131+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:27:25.130+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:27:25.169+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:27:25.162+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:27:25.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:27:25.218+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.105 seconds
[2025-01-09T05:27:55.464+0000] {processor.py:186} INFO - Started process (PID=3487) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:27:55.465+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:27:55.469+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:27:55.468+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:27:55.505+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:27:55.494+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:27:55.508+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:27:55.554+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.100 seconds
[2025-01-09T05:28:25.817+0000] {processor.py:186} INFO - Started process (PID=3553) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:28:25.819+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:28:25.824+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:28:25.823+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:28:25.858+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:28:25.850+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:28:25.863+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:28:25.902+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.097 seconds
[2025-01-09T05:28:56.549+0000] {processor.py:186} INFO - Started process (PID=3619) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:28:56.555+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:28:56.564+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:28:56.561+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:28:56.611+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:28:56.595+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:28:56.618+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:28:56.653+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.123 seconds
[2025-01-09T05:29:27.482+0000] {processor.py:186} INFO - Started process (PID=3685) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:29:27.485+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:29:27.490+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:29:27.488+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:29:27.534+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:29:27.521+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:29:27.539+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:29:27.597+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.128 seconds
[2025-01-09T05:29:57.746+0000] {processor.py:186} INFO - Started process (PID=3751) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:29:57.747+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:29:57.749+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:29:57.749+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:29:57.782+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:29:57.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:29:57.784+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:29:57.826+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.087 seconds
[2025-01-09T05:30:29.819+0000] {processor.py:186} INFO - Started process (PID=3817) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:30:29.822+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:30:29.826+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:30:29.825+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:30:29.865+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:30:29.852+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:30:29.869+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:30:29.908+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.106 seconds
[2025-01-09T05:31:00.282+0000] {processor.py:186} INFO - Started process (PID=3882) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:31:00.284+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:31:00.286+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:31:00.286+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:31:00.309+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:31:00.301+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:31:00.312+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:31:00.344+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.070 seconds
[2025-01-09T05:31:30.850+0000] {processor.py:186} INFO - Started process (PID=3946) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:31:30.851+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:31:30.853+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:31:30.853+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:31:30.890+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:31:30.884+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:31:30.892+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:31:30.937+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.096 seconds
[2025-01-09T05:32:01.488+0000] {processor.py:186} INFO - Started process (PID=4012) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:32:01.489+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:32:01.492+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:32:01.492+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:32:01.525+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:32:01.518+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:32:01.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:32:01.565+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.086 seconds
[2025-01-09T05:32:31.922+0000] {processor.py:186} INFO - Started process (PID=4074) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:32:31.924+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:32:31.927+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:32:31.927+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:32:31.963+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:32:31.954+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:32:31.966+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:32:32.002+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.091 seconds
[2025-01-09T05:33:02.087+0000] {processor.py:186} INFO - Started process (PID=4135) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:33:02.089+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:33:02.093+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:33:02.092+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:33:02.134+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:33:02.126+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:33:02.136+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:33:02.176+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.098 seconds
[2025-01-09T05:33:32.512+0000] {processor.py:186} INFO - Started process (PID=4202) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:33:32.515+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:33:32.518+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:33:32.518+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:33:32.543+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:33:32.537+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:33:32.546+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:33:32.582+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.083 seconds
[2025-01-09T05:34:02.792+0000] {processor.py:186} INFO - Started process (PID=4267) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:34:02.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:34:02.796+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:34:02.795+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:34:02.824+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:34:02.819+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:34:02.827+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:34:02.859+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.076 seconds
[2025-01-09T05:34:33.878+0000] {processor.py:186} INFO - Started process (PID=4332) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:34:33.879+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:34:33.882+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:34:33.881+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:34:33.918+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:34:33.904+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:34:33.922+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:34:33.963+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.098 seconds
[2025-01-09T05:35:06.413+0000] {processor.py:186} INFO - Started process (PID=4398) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:35:06.415+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:35:06.419+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:35:06.418+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:35:06.452+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:35:06.442+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:35:06.456+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:35:06.497+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.097 seconds
[2025-01-09T05:35:37.068+0000] {processor.py:186} INFO - Started process (PID=4460) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T05:35:37.070+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T05:35:37.072+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:35:37.072+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:35:37.100+0000] {logging_mixin.py:190} INFO - [2025-01-09T05:35:37.090+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T05:35:37.105+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T05:35:37.141+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.083 seconds
[2025-01-09T06:38:53.114+0000] {processor.py:186} INFO - Started process (PID=38) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:38:53.126+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:38:53.172+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:38:53.171+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:38:53.239+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:38:53.227+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:38:53.256+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:38:53.432+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.381 seconds
[2025-01-09T06:39:25.837+0000] {processor.py:186} INFO - Started process (PID=104) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:39:25.838+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:39:25.841+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:39:25.841+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:39:25.861+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:39:25.856+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:39:25.865+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:39:25.889+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.059 seconds
[2025-01-09T06:39:56.253+0000] {processor.py:186} INFO - Started process (PID=170) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:39:56.256+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:39:56.263+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:39:56.263+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:39:56.292+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:39:56.285+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:39:56.294+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:39:56.329+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.097 seconds
[2025-01-09T06:40:27.034+0000] {processor.py:186} INFO - Started process (PID=236) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:40:27.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:40:27.039+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:40:27.039+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:40:27.060+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:40:27.055+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:40:27.063+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:40:27.088+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.061 seconds
[2025-01-09T06:40:57.993+0000] {processor.py:186} INFO - Started process (PID=302) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:40:57.994+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:40:57.999+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:40:57.998+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:40:58.018+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:40:58.013+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:40:58.020+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:40:58.043+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.056 seconds
[2025-01-09T06:41:28.938+0000] {processor.py:186} INFO - Started process (PID=368) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:41:28.940+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:41:28.943+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:41:28.943+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:41:28.966+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:41:28.959+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:41:28.969+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:41:28.993+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.062 seconds
[2025-01-09T06:41:59.126+0000] {processor.py:186} INFO - Started process (PID=434) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:41:59.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:41:59.131+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:41:59.131+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:41:59.150+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:41:59.146+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:41:59.152+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:41:59.176+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.056 seconds
[2025-01-09T06:42:29.382+0000] {processor.py:186} INFO - Started process (PID=500) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:42:29.383+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:42:29.387+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:42:29.386+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:42:29.408+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:42:29.402+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:42:29.410+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:42:29.435+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.058 seconds
[2025-01-09T06:42:59.709+0000] {processor.py:186} INFO - Started process (PID=566) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:42:59.710+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:42:59.714+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:42:59.713+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:42:59.733+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:42:59.728+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:42:59.735+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:42:59.759+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.056 seconds
[2025-01-09T06:43:30.193+0000] {processor.py:186} INFO - Started process (PID=632) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:43:30.194+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:43:30.198+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:43:30.197+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:43:30.219+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:43:30.214+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:43:30.221+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:43:30.244+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.058 seconds
[2025-01-09T06:44:00.659+0000] {processor.py:186} INFO - Started process (PID=698) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:44:00.661+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:44:00.664+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:44:00.664+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:44:00.682+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:44:00.677+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:44:00.685+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:44:00.708+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.056 seconds
[2025-01-09T06:44:30.951+0000] {processor.py:186} INFO - Started process (PID=764) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:44:30.952+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:44:30.957+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:44:30.956+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:44:30.977+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:44:30.972+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:44:30.979+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:44:31.003+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.059 seconds
[2025-01-09T06:45:01.362+0000] {processor.py:186} INFO - Started process (PID=829) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:45:01.363+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:45:01.368+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:45:01.367+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:45:01.394+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:45:01.386+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:45:01.397+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:45:01.424+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.070 seconds
[2025-01-09T06:45:31.616+0000] {processor.py:186} INFO - Started process (PID=895) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:45:31.619+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:45:31.624+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:45:31.623+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:45:31.660+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:45:31.651+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:45:31.663+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:45:31.711+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.109 seconds
[2025-01-09T06:46:02.284+0000] {processor.py:186} INFO - Started process (PID=960) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:46:02.287+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:46:02.291+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:46:02.291+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:46:02.312+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:46:02.307+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:46:02.314+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:46:02.343+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.066 seconds
[2025-01-09T06:46:33.077+0000] {processor.py:186} INFO - Started process (PID=1026) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:46:33.078+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:46:33.082+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:46:33.082+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:46:33.103+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:46:33.098+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:46:33.105+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:46:33.130+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.061 seconds
[2025-01-09T06:47:03.611+0000] {processor.py:186} INFO - Started process (PID=1091) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:47:03.613+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:47:03.617+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:47:03.616+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:47:03.650+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:47:03.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:47:03.653+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:47:03.680+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.076 seconds
[2025-01-09T06:47:33.880+0000] {processor.py:186} INFO - Started process (PID=1157) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:47:33.883+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:47:33.887+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:47:33.886+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:47:33.907+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:47:33.901+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:47:33.909+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:47:33.933+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.061 seconds
[2025-01-09T06:48:04.707+0000] {processor.py:186} INFO - Started process (PID=1223) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:48:04.708+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:48:04.712+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:48:04.712+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:48:04.731+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:48:04.726+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:48:04.733+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:48:04.756+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.056 seconds
[2025-01-09T06:48:35.414+0000] {processor.py:186} INFO - Started process (PID=1289) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:48:35.417+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:48:35.421+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:48:35.421+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:48:35.442+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:48:35.437+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:48:35.447+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:48:35.481+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.077 seconds
[2025-01-09T06:49:05.585+0000] {processor.py:186} INFO - Started process (PID=1355) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:49:05.586+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:49:05.589+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:49:05.589+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:49:05.608+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:49:05.604+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:49:05.611+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:49:05.637+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.059 seconds
[2025-01-09T06:49:35.844+0000] {processor.py:186} INFO - Started process (PID=1421) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:49:35.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:49:35.848+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:49:35.848+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:49:35.867+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:49:35.861+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:49:35.868+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:49:35.892+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.055 seconds
[2025-01-09T06:50:06.682+0000] {processor.py:186} INFO - Started process (PID=1487) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:50:06.683+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:50:06.686+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:50:06.686+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:50:06.704+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:50:06.699+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:50:06.706+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:50:06.731+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.056 seconds
[2025-01-09T06:50:37.444+0000] {processor.py:186} INFO - Started process (PID=1553) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:50:37.446+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:50:37.451+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:50:37.451+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:50:37.478+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:50:37.470+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:50:37.483+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:50:37.541+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.112 seconds
[2025-01-09T06:51:08.166+0000] {processor.py:186} INFO - Started process (PID=1619) to work on /opt/airflow/dags/soda_checks.py
[2025-01-09T06:51:08.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/soda_checks.py for tasks to queue
[2025-01-09T06:51:08.178+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:51:08.177+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:51:08.215+0000] {logging_mixin.py:190} INFO - [2025-01-09T06:51:08.204+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/soda_checks.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/soda_checks.py", line 13, in <module>
    @task.external_python(python="/usr/local/airflow/soda_venv/bin/python")
     ^^^^
NameError: name 'task' is not defined
[2025-01-09T06:51:08.219+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/soda_checks.py
[2025-01-09T06:51:08.253+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/soda_checks.py took 0.107 seconds
